"""changed roles to use Enum and changed RentalInfo

Revision ID: 9a33632dfdf7
Revises: 376f1b92f5fc
Create Date: 2025-07-07 22:01:17.093957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a33632dfdf7'
down_revision: Union[str, Sequence[str], None] = '376f1b92f5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_info', sa.Column('deposit_amount', sa.Integer(), nullable=False))
    op.add_column('rental_info', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('role_type', sa.Enum('ADMIN', 'CLIENT', 'OWNER', 'AGENT', 'INVESTOR', name='role_enum', native_enum=False), nullable=False))
    op.drop_column('role', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('role', 'role_type')
    op.drop_column('rental_info', 'created_at')
    op.drop_column('rental_info', 'deposit_amount')
    # ### end Alembic commands ###
